export const USER_AUTHENTICATE = 'USER_AUTHENTICATE'
export const USER_AUTHENTICATE_SUCCESS = 'USER_AUTHENTICATE_SUCCESS'
export const USER_AUTHENTICATE_FAILURE = 'USER_AUTHENTICATE_FAILURE'
export const USER_AUTHENTICATE_HIDE_ERROR = 'USER_AUTHENTICATE_HIDE_ERROR'
export const USER_GET_MENU_OPTIONS = 'USER_GET_MENU_OPTIONS'
export const USER_GET_MENU_OPTIONS_SUCESS = 'USER_GET_MENU_OPTIONS_SUCESS'
export const USER_GET_MENU_OPTIONS_FAILURE = 'USER_GET_MENU_OPTIONS_FAILURE'
export const BUSINESS_GET_INFO = 'BUSINESS_GET_INFO'
export const BUSINESS_GET_INFO_SUCESS = 'BUSINESS_GET_INFO_SUCESS'
export const BUSINESS_GET_INFO_FAILURE = 'BUSINESS_GET_INFO_FAILURE'
export const PARTNERS_GET_PARTNERS = 'PARTNERS_GET_PARTNERS'
export const PARTNERS_GET_PARTNERS_SUCCESS = 'PARTNERS_GET_PARTNERS_SUCCESS'
export const PARTNERS_GET_PARTNERS_FAILURE = 'PARTNERS_GET_PARTNERS_FAILURE'
export const GENERAL_GET_NATIONALITIES = 'GENERAL_GET_NATIONALITIES'
export const GENERAL_GET_NATIONALITIES_SUCCESS =
  'GENERAL_GET_NATIONALITIES_SUCCESS'
export const GENERAL_GET_NATIONALITIES_FAILURE =
  'GENERAL_GET_NATIONALITIES_FAILURE'
export const CATCHEMENTS_GET_PRODUCT_RANGES = 'CATCHEMENTS_GET_PRODUCT_RANGES'
export const CATCHEMENTS_GET_PRODUCT_RANGES_SUCCESS =
  'CATCHEMENTS_GET_PRODUCT_RANGES_SUCCESS'
export const CATCHEMENTS_GET_PRODUCT_RANGES_FAILURE =
  'CATCHEMENTS_GET_PRODUCT_RANGES_FAILURE'
