export const LOGIN_AUTHENTICATE = 'LOGIN_AUTHENTICATE';
export const LOGIN_AUTHENTICATE_SUCCESS = 'LOGIN_AUTHENTICATE_SUCCESS';
export const LOGIN_AUTHENTICATE_FAILURE = 'LOGIN_AUTHENTICATE_FAILURE';
